In [1]:
import numpy as np
from neuralnet.activation import Sigmoid, ReLu, Softmax
from neuralnet.utils import normalize, one_hot_encoding
from neuralnet.model import Model, Layer

In [2]:
def cross_entropy(logits,one_hot_label):
    label = np.where(one_hot_label == 1)[0]
    prod = np.log(logits[np.arange(len(logits)),label])
    return -np.sum(prod)

In [3]:
sigmoid_obj = Sigmoid()
sigmoid_obj.forward(np.array([-1,2,3]))

array([0.26894142, 0.88079708, 0.95257413])

In [4]:
relu_obj = ReLu()
post = relu_obj.forward(np.array([-1,2,3]))
relu_obj.backward(post)

array([0, 1, 1])

In [5]:
data = [1,2,134,20,29341,23]
x = np.array(normalize(data))
if x.ndim==1:
    x = np.expand_dims(x,axis=0)
layer1 = Layer(in_feature=x.shape[1], out_feature=10,activation=ReLu())
layer2 = Layer(in_feature=10, out_feature=100,activation=ReLu())
layer3 = Layer(in_feature=100, out_feature=3,activation=Softmax())

In [6]:
model = Model(layer1, layer2, layer3)
model.compile(cross_entropy)

In [7]:
y = np.array([0])
y = one_hot_encoding(y,num_classes=3)

In [8]:
print('Weights before forward')
model.get_weights()

Weights before forward


[array([[-0.24760267, -0.59303793,  0.39267276, -0.01085782, -0.43043542,
          0.30053088,  0.06565707, -0.24951253,  0.17368114, -0.48618548],
        [-0.07055331, -0.39980498,  0.48263808, -0.49510693,  0.16219453,
         -0.03859748, -0.10058598, -0.48011977,  0.52615792, -0.58408537],
        [-0.30630954, -0.59968139, -0.1916466 ,  0.05027676,  0.02953203,
          0.30850944,  0.05018409,  0.10111357,  0.52698505,  0.07741247],
        [-0.45570704,  0.32282896,  0.55969925, -0.07364248, -0.21584318,
         -0.17493798,  0.57338988, -0.39440993,  0.18351456, -0.07650146],
        [-0.4844542 , -0.05651178, -0.16933924, -0.46559065, -0.02644996,
         -0.54697069,  0.1220417 ,  0.44497374, -0.04284787, -0.35567732],
        [ 0.12913783,  0.43161487, -0.31832265, -0.42872989, -0.30141507,
          0.54203811,  0.16055521, -0.54166637,  0.0938028 ,  0.53436799]]),
 array([[ 1.03889066e-01,  1.69176624e-01,  2.13443074e-01,
          9.72269628e-03, -1.80330275e-01,  

In [9]:
logits, loss= model.forward(x,y)

In [10]:
print('Weights after forward')
model.get_weights()

Weights after forward


[array([[-0.24760267, -0.59303793,  0.39267276, -0.01085782, -0.43043542,
          0.30053088,  0.06565707, -0.24951253,  0.17368114, -0.48618548],
        [-0.07055331, -0.39980498,  0.48263808, -0.49510693,  0.16219453,
         -0.03859748, -0.10058598, -0.48011977,  0.52615792, -0.58408537],
        [-0.30630954, -0.59968139, -0.1916466 ,  0.05027676,  0.02953203,
          0.30850944,  0.05018409,  0.10111357,  0.52698505,  0.07741247],
        [-0.45570704,  0.32282896,  0.55969925, -0.07364248, -0.21584318,
         -0.17493798,  0.57338988, -0.39440993,  0.18351456, -0.07650146],
        [-0.4844542 , -0.05651178, -0.16933924, -0.46559065, -0.02644996,
         -0.54697069,  0.1220417 ,  0.44497374, -0.04284787, -0.35567732],
        [ 0.12913783,  0.43161487, -0.31832265, -0.42872989, -0.30141507,
          0.54203811,  0.16055521, -0.54166637,  0.0938028 ,  0.53436799]]),
 array([[ 1.03889066e-01,  1.69176624e-01,  2.13443074e-01,
          9.72269628e-03, -1.80330275e-01,  

In [11]:
model.backward()
model.step(0.1)

In [12]:
print('Weights after 1 step')
model.get_weights()

Weights after 1 step


[array([[-0.24760267, -0.59303793,  0.39267276, -0.01085782, -0.43043542,
          0.30053088,  0.06565659, -0.24951332,  0.17368114, -0.48618548],
        [-0.07055331, -0.39980498,  0.48263808, -0.49510693,  0.16219453,
         -0.03859748, -0.10058694, -0.48012137,  0.52615792, -0.58408537],
        [-0.30630954, -0.59968139, -0.1916466 ,  0.05027676,  0.02953203,
          0.30850944,  0.05011963,  0.10100662,  0.52698505,  0.07741247],
        [-0.45570704,  0.32282896,  0.55969925, -0.07364248, -0.21584318,
         -0.17493798,  0.57338026, -0.3944259 ,  0.18351456, -0.07650146],
        [-0.4844542 , -0.05651178, -0.16933924, -0.46559065, -0.02644996,
         -0.54697069,  0.10792737,  0.42155593, -0.04284787, -0.35567732],
        [ 0.12913783,  0.43161487, -0.31832265, -0.42872989, -0.30141507,
          0.54203811,  0.16054414, -0.54168473,  0.0938028 ,  0.53436799]]),
 array([[ 1.03889066e-01,  1.69176624e-01,  2.13443074e-01,
          9.72269628e-03, -1.80330275e-01,  