In [16]:
import numpy as np
from neuralnet.activation import Sigmoid, ReLu, Softmax
from neuralnet.utils import normalize, one_hot_encoding
from neuralnet.model import Model, Layer

In [17]:
def cross_entropy(logits,one_hot_label):
    label = np.where(one_hot_label == 1)[0]
    prod = np.log(logits[np.arange(len(logits)),label])
    return -np.sum(prod)

In [18]:
sigmoid_obj = Sigmoid()
sigmoid_obj.forward(np.array([-1,2,3]))

array([0.26894142, 0.88079708, 0.95257413])

In [19]:
relu_obj = ReLu()
post = relu_obj.forward(np.array([-1,2,3]))
relu_obj.backward(post)

array([0, 1, 1])

In [20]:
data = [1,2,134,20,29341,23]
x = np.array(normalize(data))
if x.ndim==1:
    x = np.expand_dims(x,axis=0)
layer1 = Layer(in_feature=x.shape[1], out_feature=10,activation=ReLu())
layer2 = Layer(in_feature=10, out_feature=100,activation=ReLu())
layer3 = Layer(in_feature=100, out_feature=3,activation=Softmax())

In [21]:
model = Model(layer1, layer2, layer3)
model.compile(cross_entropy)

In [22]:
y = np.array([0])
y = one_hot_encoding(y,num_classes=3)

In [23]:
print('Weights before forward')
model.get_weights()

Weights before forward


[array([[-0.10096839, -0.579231  ,  0.33866629,  0.11708749,  0.40640543,
         -0.4025994 ,  0.27179257,  0.36759374, -0.41034321, -0.05968193],
        [ 0.14669779, -0.12178971, -0.15882726, -0.33205379, -0.12138832,
         -0.20943296,  0.07043152,  0.16474546, -0.48824882,  0.38616005],
        [-0.35014457,  0.2496831 , -0.43642366,  0.25798718, -0.29225768,
          0.04079824,  0.36900691,  0.01595771, -0.00947151,  0.5897628 ],
        [-0.00747282, -0.27284896,  0.45192529, -0.27944568,  0.23368185,
          0.24728084, -0.59107936, -0.15590763, -0.11621141, -0.29675432],
        [-0.38135499,  0.40695948,  0.25169274, -0.32487871, -0.08693451,
          0.47399638, -0.24993429, -0.1663084 ,  0.39792547,  0.25464446],
        [-0.21676485, -0.03015941, -0.39639366, -0.41730354, -0.60544423,
          0.44203177, -0.11106152, -0.5774643 , -0.26947689, -0.53670771]]),
 array([[ 1.66200166e-01, -1.42098890e-01,  1.16403606e-01,
         -1.19357339e-01,  9.22171191e-02, -

In [24]:
logits, loss= model.forward(x,y)

In [25]:
print('Weights after forward')
model.get_weights()

Weights after forward


[array([[-0.10096839, -0.579231  ,  0.33866629,  0.11708749,  0.40640543,
         -0.4025994 ,  0.27179257,  0.36759374, -0.41034321, -0.05968193],
        [ 0.14669779, -0.12178971, -0.15882726, -0.33205379, -0.12138832,
         -0.20943296,  0.07043152,  0.16474546, -0.48824882,  0.38616005],
        [-0.35014457,  0.2496831 , -0.43642366,  0.25798718, -0.29225768,
          0.04079824,  0.36900691,  0.01595771, -0.00947151,  0.5897628 ],
        [-0.00747282, -0.27284896,  0.45192529, -0.27944568,  0.23368185,
          0.24728084, -0.59107936, -0.15590763, -0.11621141, -0.29675432],
        [-0.38135499,  0.40695948,  0.25169274, -0.32487871, -0.08693451,
          0.47399638, -0.24993429, -0.1663084 ,  0.39792547,  0.25464446],
        [-0.21676485, -0.03015941, -0.39639366, -0.41730354, -0.60544423,
          0.44203177, -0.11106152, -0.5774643 , -0.26947689, -0.53670771]]),
 array([[ 1.66200166e-01, -1.42098890e-01,  1.16403606e-01,
         -1.19357339e-01,  9.22171191e-02, -

In [26]:
model.backward()
model.step(0.1)

In [27]:
print('Weights after 1 step')
model.get_weights()

Weights after 1 step


[array([[-0.10096839, -0.57923147,  0.33866609,  0.11708749,  0.40640543,
         -0.40259951,  0.27179257,  0.36759374, -0.4103427 , -0.05968196],
        [ 0.14669779, -0.12179066, -0.15882767, -0.33205379, -0.12138832,
         -0.20943319,  0.07043152,  0.16474546, -0.48824781,  0.38615999],
        [-0.35014457,  0.24961948, -0.43645137,  0.25798718, -0.29225768,
          0.04078309,  0.36900691,  0.01595771, -0.00940397,  0.5897589 ],
        [-0.00747282, -0.27285846,  0.45192115, -0.27944568,  0.23368185,
          0.24727858, -0.59107936, -0.15590763, -0.11620133, -0.2967549 ],
        [-0.38135499,  0.39302945,  0.24562678, -0.32487871, -0.08693451,
          0.47067949, -0.24993429, -0.1663084 ,  0.41271511,  0.25379057],
        [-0.21676485, -0.03017033, -0.39639841, -0.41730354, -0.60544423,
          0.44202917, -0.11106152, -0.5774643 , -0.2694653 , -0.53670838]]),
 array([[ 1.66200166e-01, -1.42098890e-01,  1.16403606e-01,
         -1.19357339e-01,  9.22171191e-02, -

In [28]:
from neuralnet.datastructure import Node, LinkedList

In [29]:
mylist = LinkedList()
mylist.insert_head(Node(["THis is head1"]))
mylist.insert_head(Node("THis is head2"))
mylist.insert_head(Node("THis is head3"))
mylist.insert_head(Node("THis is head4"))

In [30]:
for node in mylist:
    print(node)

THis is head4
THis is head3
THis is head2
['THis is head1']
